controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

apis:
    resource:
        path: ../src/Api/
        namespace: App\Api
    prefix: /api
    type: attribute

api_login_check:
    path: /api/login